package com.salo.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUserRate<M extends BaseUserRate<M>> extends Model<M> implements IBean {

	public M setUserId(java.lang.Integer userId) {
		set("userId", userId);
		return (M)this;
	}
	
	public java.lang.Integer getUserId() {
		return getInt("userId");
	}

	public M setRatedUserId(java.lang.Integer ratedUserId) {
		set("ratedUserId", ratedUserId);
		return (M)this;
	}
	
	public java.lang.Integer getRatedUserId() {
		return getInt("ratedUserId");
	}

	public M setRate(java.lang.Integer rate) {
		set("rate", rate);
		return (M)this;
	}
	
	public java.lang.Integer getRate() {
		return getInt("rate");
	}

	public M setRateTime(java.util.Date rateTime) {
		set("rateTime", rateTime);
		return (M)this;
	}
	
	public java.util.Date getRateTime() {
		return get("rateTime");
	}

}
