package com.salo.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUserInfo<M extends BaseUserInfo<M>> extends Model<M> implements IBean {

	public M setUserId(java.lang.Integer userId) {
		set("userId", userId);
		return (M)this;
	}
	
	public java.lang.Integer getUserId() {
		return getInt("userId");
	}

	public M setUserName(java.lang.String userName) {
		set("userName", userName);
		return (M)this;
	}
	
	public java.lang.String getUserName() {
		return getStr("userName");
	}

	public M setInvitationCode(java.lang.String invitationCode) {
		set("invitationCode", invitationCode);
		return (M)this;
	}
	
	public java.lang.String getInvitationCode() {
		return getStr("invitationCode");
	}

	public M setPhoneNum(java.lang.String phoneNum) {
		set("phoneNum", phoneNum);
		return (M)this;
	}
	
	public java.lang.String getPhoneNum() {
		return getStr("phoneNum");
	}

	public M setPwd(java.lang.String pwd) {
		set("pwd", pwd);
		return (M)this;
	}
	
	public java.lang.String getPwd() {
		return getStr("pwd");
	}

	public M setDescription(java.lang.String description) {
		set("description", description);
		return (M)this;
	}
	
	public java.lang.String getDescription() {
		return getStr("description");
	}

	public M setPortraitUrl(java.lang.String portraitUrl) {
		set("portraitUrl", portraitUrl);
		return (M)this;
	}
	
	public java.lang.String getPortraitUrl() {
		return getStr("portraitUrl");
	}

	public M setWechatID(java.lang.String wechatID) {
		set("wechatID", wechatID);
		return (M)this;
	}
	
	public java.lang.String getWechatID() {
		return getStr("wechatID");
	}

	public M setUserType(java.lang.Integer userType) {
		set("userType", userType);
		return (M)this;
	}
	
	public java.lang.Integer getUserType() {
		return getInt("userType");
	}

	public M setSex(java.lang.Integer sex) {
		set("sex", sex);
		return (M)this;
	}
	
	public java.lang.Integer getSex() {
		return getInt("sex");
	}

	public M setIsAuthenticated(java.lang.Integer isAuthenticated) {
		set("isAuthenticated", isAuthenticated);
		return (M)this;
	}
	
	public java.lang.Integer getIsAuthenticated() {
		return getInt("isAuthenticated");
	}

	public M setRate(java.lang.Double rate) {
		set("rate", rate);
		return (M)this;
	}
	
	public java.lang.Double getRate() {
		return getDouble("rate");
	}

	public M setRegisterTime(java.util.Date registerTime) {
		set("registerTime", registerTime);
		return (M)this;
	}
	
	public java.util.Date getRegisterTime() {
		return get("registerTime");
	}

}
