package com.salo.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUserType<M extends BaseUserType<M>> extends Model<M> implements IBean {

	public M setTypeId(java.lang.Integer typeId) {
		set("typeId", typeId);
		return (M)this;
	}
	
	public java.lang.Integer getTypeId() {
		return getInt("typeId");
	}

	public M setTypeName(java.lang.String typeName) {
		set("typeName", typeName);
		return (M)this;
	}
	
	public java.lang.String getTypeName() {
		return getStr("typeName");
	}

}
