package com.salo.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUserTag<M extends BaseUserTag<M>> extends Model<M> implements IBean {

	public M setUserId(java.lang.Integer userId) {
		set("userId", userId);
		return (M)this;
	}
	
	public java.lang.Integer getUserId() {
		return getInt("userId");
	}

	public M setTagId(java.lang.Integer tagId) {
		set("tagId", tagId);
		return (M)this;
	}
	
	public java.lang.Integer getTagId() {
		return getInt("tagId");
	}

}
