package com.salo.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BasePicture<M extends BasePicture<M>> extends Model<M> implements IBean {

	public M setPicId(java.lang.Integer picId) {
		set("picId", picId);
		return (M)this;
	}
	
	public java.lang.Integer getPicId() {
		return getInt("picId");
	}

	public M setPicUrl(java.lang.String picUrl) {
		set("picUrl", picUrl);
		return (M)this;
	}
	
	public java.lang.String getPicUrl() {
		return getStr("picUrl");
	}

	public M setUploadTime(java.util.Date uploadTime) {
		set("uploadTime", uploadTime);
		return (M)this;
	}
	
	public java.util.Date getUploadTime() {
		return get("uploadTime");
	}

	public M setUploaderId(java.lang.Integer uploaderId) {
		set("uploaderId", uploaderId);
		return (M)this;
	}
	
	public java.lang.Integer getUploaderId() {
		return getInt("uploaderId");
	}

}
