package com.salo.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseGender<M extends BaseGender<M>> extends Model<M> implements IBean {

	public M setGenderId(java.lang.Integer genderId) {
		set("genderId", genderId);
		return (M)this;
	}
	
	public java.lang.Integer getGenderId() {
		return getInt("genderId");
	}

	public M setGenderName(java.lang.String genderName) {
		set("genderName", genderName);
		return (M)this;
	}
	
	public java.lang.String getGenderName() {
		return getStr("genderName");
	}

}
