package com.salo.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseFollow<M extends BaseFollow<M>> extends Model<M> implements IBean {

	public M setUserId(java.lang.Integer userId) {
		set("userId", userId);
		return (M)this;
	}
	
	public java.lang.Integer getUserId() {
		return getInt("userId");
	}

	public M setFollowUserId(java.lang.Integer followUserId) {
		set("followUserId", followUserId);
		return (M)this;
	}
	
	public java.lang.Integer getFollowUserId() {
		return getInt("followUserId");
	}

}
