package com.salo.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("auth", "authId", Auth.class);
		// Composite Primary Key order: followUserId,userId
		arp.addMapping("follow", "followUserId,userId", Follow.class);
		arp.addMapping("gender", "genderId", Gender.class);
		arp.addMapping("picture", "picId", Picture.class);
		arp.addMapping("tag", "tagId", Tag.class);
		arp.addMapping("user_info", "userId", UserInfo.class);
		// Composite Primary Key order: ratedUserId,userId
		arp.addMapping("user_rate", "ratedUserId,userId", UserRate.class);
		// Composite Primary Key order: tagId,userId
		arp.addMapping("user_tag", "tagId,userId", UserTag.class);
		arp.addMapping("user_type", "typeId", UserType.class);
	}
}

