package com.salo.model;

import com.salo.model.base.BaseUserRate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserRate extends BaseUserRate<UserRate> {
	public static final UserRate dao = new UserRate().dao();
}
