package com.salo.model;

import com.salo.model.base.BaseUserTag;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserTag extends BaseUserTag<UserTag> {
	public static final UserTag dao = new UserTag().dao();
}
